services:
  - type: web
    name: stockanalyzer-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production 